java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../webapp/static/js/easyui-1.4/extend/js/easyui-extend.js -o ../webapp/static/js/easyui-1.4/extend/js/easyui-extend-min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../webapp/static/js/easyui-1.4/extend/js/validatebox-extend.js -o ../webapp/static/js/easyui-1.4/extend/js/validatebox-extend-min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../webapp/static/js/easyui-1.4/extend/js/validatebox-ajax.js -o ../webapp/static/js/easyui-1.4/extend/js/validatebox-ajax-min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../webapp/static/js/jquery/jquery-extend.js -o ../webapp/static/js/jquery/jquery-extend-min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../webapp/static/js/jquery/jquery.cookie.js -o ../webapp/static/js/jquery/jquery.cookie-min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../webapp/static/js/easyui-1.4/datagridview/datagrid-scrollview.js -o ../webapp/static/js/easyui-1.4/datagridview/datagrid-scrollview-min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../webapp/static/js/easyui-1.4/jquery.easyui.my97.js -o ../webapp/static/js/easyui-1.4/jquery.easyui.my97-min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../webapp/static/js/easyui-1.4/datagridview/datagrid-scrollview2.js -o ../webapp/static/js/easyui-1.4/datagridview/datagrid-scrollview2-min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../webapp/static/js/easyui-1.4/datagridview/datagrid-bufferview.js -o ../webapp/static/js/easyui-1.4/datagridview/datagrid-bufferview-min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../webapp/static/js/easyui-1.4/datagridview/datagrid-groupview.js -o ../webapp/static/js/easyui-1.4/datagridview/datagrid-groupview-min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../webapp/static/js/easyui-1.4/extend/app/jquery.app.js -o ../webapp/static/js/easyui-1.4/extend/app/jquery.app-min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../webapp/static/js/easyui-1.4/extend/app/initApp.js -o ../webapp/static/js/easyui-1.4/extend/app/initApp-min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../webapp/static/js/easyui-1.4/portal/jquery.portal.js -o ../webapp/static/js/easyui-1.4/portal/jquery.portal-min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../webapp/static/js/jquery/uploadify/scripts/jquery.uploadify.mine.js -o ../webapp/static/js/jquery/uploadify/scripts/jquery.uploadify.mine-min.js